<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-04T14:31:37 IST" name="Default suite" finished-at="2023-02-04T14:31:39 IST" duration-ms="2525">
    <groups>
    </groups>
    <test started-at="2023-02-04T14:31:37 IST" name="Default test" finished-at="2023-02-04T14:31:39 IST" duration-ms="2525">
      <class name="basic_cal.division">
        <test-method signature="setup()[pri:0, instance:basic_cal.division@34448e6c]" started-at="2023-02-04T14:31:37 IST" name="setup" finished-at="2023-02-04T14:31:37 IST" duration-ms="851" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="division_TC_01()[pri:0, instance:basic_cal.division@34448e6c]" started-at="2023-02-04T14:31:37 IST" name="division_TC_01" finished-at="2023-02-04T14:31:38 IST" depends-on-methods="basic_cal.division.setup" duration-ms="512" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
result is not matching expected [2] but found [2.00]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
result is not matching expected [2] but found [2.00]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at basic_cal.division.division_TC_01(division.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- division_TC_01 -->
        <test-method signature="division_TC_02()[pri:0, instance:basic_cal.division@34448e6c]" started-at="2023-02-04T14:31:38 IST" name="division_TC_02" finished-at="2023-02-04T14:31:38 IST" depends-on-methods="basic_cal.division.setup" duration-ms="442" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- division_TC_02 -->
        <test-method signature="division_TC_03()[pri:0, instance:basic_cal.division@34448e6c]" started-at="2023-02-04T14:31:38 IST" name="division_TC_03" finished-at="2023-02-04T14:31:39 IST" depends-on-methods="basic_cal.division.setup" duration-ms="425" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- division_TC_03 -->
        <test-method is-config="true" signature="tear()[pri:0, instance:basic_cal.division@34448e6c]" started-at="2023-02-04T14:31:39 IST" name="tear" finished-at="2023-02-04T14:31:39 IST" duration-ms="208" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear -->
      </class> <!-- basic_cal.division -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
